name: akhbary
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite:
  intl: <=0.17.0
  conditional_builder_null_safety: ^0.0.6
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dio: ^5.0.0
  hexcolor: ^3.0.1
  shared_preferences: ^2.0.17
  webview_flutter: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true